#ifndef SCENE_EVENTS_HPP
#define SCENE_EVENTS_HPP

enum SCENE_EVENT {
    EVT_SCENE_DESTROYED,
    EVT_OBJECT_CREATED,
    EVT_OBJECT_REMOVED,
    EVT_COMPONENT_CREATED,
    EVT_COMPONENT_REMOVED
};

#endif
